/** Represents a single note */
export interface Note {
  id: string; // Generated by crypto.randomUUID
  title: string;
  content: string;
  createdAt: number; // Unix timestamp
  updatedAt: number; // Unix timestamp
}
