/** Represents a single note */
export interface Note {
  id: string; // Generated by crypto.randomUUID
  title: string;
  content: string;

  // timestamps from Date.now
  createdAt: number;
  updatedAt: number;
}
